//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;

namespace KhadimiEssa.Resources
{
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SharedResource
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResource()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hamlity.Resources.SharedResource", typeof(SharedResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يرجى التاكد من البيانات.
        /// </summary>
        public static string CheckData
        {
            get
            {
                return ResourceManager.GetString("CheckData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم ارسال الكود.
        /// </summary>
        public static string CodeSent
        {
            get
            {
                return ResourceManager.GetString("CodeSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يرجى التحقق من الكود.
        /// </summary>
        public static string ConfirmCode
        {
            get
            {
                return ResourceManager.GetString("ConfirmCode", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to من فضلك تاكد من كلمة المرور.
        /// </summary>
        public static string ConfirmPassword
        {
            get
            {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا  الايميل موجود بالفعل.
        /// </summary>
        public static string ExistEmail
        {
            get
            {
                return ResourceManager.GetString("ExistEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الهاتف موجود بالفعل.
        /// </summary>
        public static string ExistPhone
        {
            get
            {
                return ResourceManager.GetString("ExistPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يرجى ادخل بريد الكترونى صحيح.
        /// </summary>
        public static string InvalidEmail
        {
            get
            {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب الا تقل كلمة المرور عن 6 احرف او ارقام ولا تزيد عن 100.
        /// </summary>
        public static string LengthPassword
        {
            get
            {
                return ResourceManager.GetString("LengthPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to يجب ان يكون ارقام والا يقل رقم الهاتف عن 10 ارقام.
        /// </summary>
        public static string LengthPhone
        {
            get
            {
                return ResourceManager.GetString("LengthPhone", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب مغلق من قبل الادمن.
        /// </summary>
        public static string LockedAdmin
        {
            get
            {
                return ResourceManager.GetString("LockedAdmin", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب لم يفعل بعد.
        /// </summary>
        public static string NotActivated
        {
            get
            {
                return ResourceManager.GetString("NotActivated", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to عذرا هذا الهاتف غير مسجل لدينا.
        /// </summary>
        public static string NotRegistered
        {
            get
            {
                return ResourceManager.GetString("NotRegistered", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور بنجاح.
        /// </summary>
        public static string Passwordchanged
        {
            get
            {
                return ResourceManager.GetString("Passwordchanged", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور غير مطابقة.
        /// </summary>
        public static string Passwordmatch
        {
            get
            {
                return ResourceManager.GetString("Passwordmatch", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to رقم الهاتف غير صحيح.
        /// </summary>
        public static string PhoneIncorrect
        {
            get
            {
                return ResourceManager.GetString("PhoneIncorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to هذا الحقل مطلوب.
        /// </summary>
        public static string required
        {
            get
            {
                return ResourceManager.GetString("required", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ ما.
        /// </summary>
        public static string wrong
        {
            get
            {
                return ResourceManager.GetString("wrong", resourceCulture);
            }
        }
    }
}
